triggers:
  - dirs: [., src]
    cmd: echo
    args: ['hello!']

  - name: test case 1
    dirs: [., src]
    cmd: echo
    args: ['hello!']

  - name: minification
    dirs: [.]
    cmd: echo
    args: [bloop]
